### ISSUE TITLE
error: ‘class ncnn::Extractor’ has no member named ‘opt’

### ISSUE THREAD

**Issue by jcyhcs** [HonglinChu/NanoTrack#1]
hi,professor:
i compile your example code nanotrack-macos, i got an error:
**_error: ‘class ncnn::Extractor’ has no member named ‘opt’
     ex_backbone.opt.use_vulkan_compute = true;_**
why got this compile error?
i use ncnn-20220420-full-source.zip, ncnn is compile from this source code.
please HELP!

**Comment by HonglinChu** [comment]
> hi,professor: i compile your example code nanotrack-macos, i got an error: **_error: ‘class ncnn::Extractor’ has no member named ‘opt’ ex_backbone.opt.use_vulkan_compute = true;_** why got this compile error? i use ncnn-20220420-full-source.zip, ncnn is compile from this source code. please HELP!

The ncnn version may be inconsistent.
