### ISSUE TITLE
some question about backbone net input size?

### ISSUE THREAD

**Issue by jcyhcs** [HonglinChu/NanoTrack#3]
hi,professor:
i fllow your code, and try convert to tensorrt code, i convert backbone net to onnx format ok, i use netron , then input size is 
![image](https://user-images.githubusercontent.com/34532224/168043481-7da170df-52c8-4828-9367-ffb33c4a26b8.png)
,but i debug your ncnn-macos code, i find code below:
    **_ncnn::Mat ncnn_img = ncnn::Mat::from_pixels(z_crop.data, ncnn::Mat::PIXEL_BGR2RGB, z_crop.cols, z_crop.rows);
    printf("ncnn_img.w:%d,ncnn_img.h:%d\n",ncnn_img.w,ncnn_img.h);_**
the result is ncnn_img.w=127, ncnn_img.h=127;
so, what the real size for backbone input node??
how can i deal with this problem?
PLEASE HELP!

**Comment by HonglinChu** [comment]
> hi,professor: i fllow your code, and try convert to tensorrt code, i convert backbone net to onnx format ok, i use netron , then input size is ![image](https://user-images.githubusercontent.com/34532224/168043481-7da170df-52c8-4828-9367-ffb33c4a26b8.png) ,but i debug your ncnn-macos code, i find code below: **_ncnn::Mat ncnn_img = ncnn::Mat::from_pixels(z_crop.data, ncnn::Mat::PIXEL_BGR2RGB, z_crop.cols, z_crop.rows); printf("ncnn_img.w:%d,ncnn_img.h:%d\n",ncnn_img.w,ncnn_img.h);_** the result is ncnn_img.w=127, ncnn_img.h=127; so, what the real size for backbone input node?? how can i deal with this problem? PLEASE HELP!

NCNN supports adaptive scale input. And the initial template size is [1,3,127,127], search template size is [1,3,255,255]

**Comment by jcyhcs** [comment]
hi,professor:
i have success run NanoTrack on jetson tx2 with TensorRT accelerate! it very fast, fps almost 77fps~122fps!
but i test the dance_girl.mp4, i find the track not very good, always have lost and track error! 
the result is same with ncnn version.
i upload the result video of dance_girl, please tell me why NanoTrack is poor performance, and how to make it more better?
